services:
  borders:
    image: melsincostan/borders
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      # the time zone of the administrator should be here
      - TZ=Europe/Paris
      - DB_FILE=/data/borders.db
      - JWT_KEY_FILE=/data/key.bin
      # these values are examples, with the default value set.
      # - SERVE_PORT=8080
      # - JWT_KEY_LENGTH=16
    volumes:
      - ./data:/data:rw